#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"

ZOPEN_TARBALL_DIR=gawk-5.1.1
export ZOPEN_TARBALL_URL="https://git.savannah.gnu.org/cgit/gawk.git/snapshot/${ZOPEN_TARBALL_DIR}.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make diffutils"
export ZOPEN_EXTRA_CPPFLAGS="-DATTRIBUTE_NORETURN=_Noreturn"

export ZOPEN_BOOTSTRAP=skip

zopen_check_results()
{
  return 3 # non-functional
}

